### PR TITLE
fix/ add view post links

### LINKED ISSUE #188: frontend : send user to view post page on clicking a post
frontend : send user to view post page on clicking a post

### PR DESCRIPTION
**Pull request by avinash360**
Closes #188 
## Types of changes
- [x] Add tags to auto close the corresponding issue.
- [x] I followed branch and commit naming convention.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: client/src/components/BlogCard/index.jsx [hunk 1]
```diff
@@ -1,17 +1,17 @@
...
 export default function BlogCard({ data }) {
   const {
-    category, title, content, author, image,
+    category, title, content, author, image, _id,
   } = data;
-
   return (
     <div className={styles.container}>
-      <a className={styles.cardLink} href="">
+      <Link className={styles.cardLink} to={`/post/${_id}`}>
```
Comment (sumeetrohra) [inline client/src/components/BlogCard/index.jsx]: Don't use link here, use a tag with href as the path

Comment (avinash360) [reply client/src/components/BlogCard/index.jsx]: react router dom handles browser's back button action better as compared to while using the same with an anchor
