### PR TITLE
Fix/Markdown component when URL is incomplete/

### LINKED ISSUE #176: Fix Markdown when video URL is incomplete

### PR DESCRIPTION
**Pull request by Navneet-Sahota**
close #176

## Types of changes

- [x] Add tags to auto close the corresponding issue.
- [x] I followed branch and commit naming convention.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: client/src/components/plugin/index.js [hunk 1]
```diff
@@ -1,7 +1,41 @@
...
+    disabled: false,
+    replace: [
+      ['http://', 'https://'],
+    ],
+    removeAfter: '&',
+  },
+};
 
-export default plugins;
+const youtubePluginProperties = {
```
Comment (avinash360) [inline client/src/components/plugin/index.js]: @Navneet-Sahota have you checked for responsiveness?

Comment (Navneet-Sahota) [reply client/src/components/plugin/index.js]: Yes
