### PR TITLE
fix/Add user Id check in backend

### LINKED ISSUE #131: Add user Id check in backend

### PR DESCRIPTION
**Pull request by sumeetrohra**
close #131

## Types of changes

- [x] Add tags to auto close the corresponding issue.
- [x] I followed branch and commit naming convention.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: client/src/config/axiosConfig.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 const config = {};
 
-if (process.env.NODE_ENV === 'production') {
+if (process.env.NODE_ENV !== 'production') {
```
Comment (Navneet-Sahota) [inline client/src/config/axiosConfig.js]: Why this?
